server:
  port: 8080
  servlet:
    context-path: /pay

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

spring:
  application:
    name: ldh-pay
  ###数据库相关连接
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ldh-pay
mybatis:
  mapper-locations: classpath*:com/liudehuang/**/mapper/*.xml

#------redis配置---------
dj:
  redis:
    open-cluster: false  #是否启动集群配置
    single-redis:
      database: 5 #哪个库
      host: 127.0.0.1 #地址
      password: 123456 #单机密码
      port: 6379
      timeout: 6000 #超时时间